name: tf-destroy-jenkins-dev
on: 
  workflow_dispatch:

env:
  deploy_region: "eu-central-1"
  environment: dev

jobs:
  destroy-tf-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: ${{ env.deploy_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform destroy
        id: tf-destroy
        run: |
          cd terraform
          terraform init
          terraform destroy -auto-approve
        shell: bash
